### ISSUE TITLE
Requests de Inicio sesión para el segundo Sprint.

### ISSUE THREAD

**Issue by robertocml** [armandoalamilla/FYCT#2]
### Requests de Inicio sesión para el segundo Sprint. (Marzo 2, 2019)

- El sistema permitirá el inicio de sesión de un usuario sólo cuando éste provea las credenciales correctas (usuario o correo, y contraseña)

- El sistema permitirá al usuario regresar a la página de Hogar desde la página Inicio sesión al dar click en el logotipo de la empresa

### To-do

- [x] Agregar el href="/" al anchor del logo en login.html (Para que el logo rediriga a home)

**Comment by armandoalamilla** [comment]
ya quedo corregido
